// src/features/profile/edit/profileEdit.constants.ts

/*
these are features that are company specifc
*/


export const INDUSTRIES: { title: string; options: string[] }[] = [
  { title: "Technology", options: ["Software & IT", "Hardware & Electronics", "Telecom", "Internet & Digital Services"] },
  { title: "Healthcare & Life Sciences", options: ["Healthcare Services", "Pharmaceuticals & Biotechnology", "Medical Devices", "Health Insurance"] },
  { title: "Financial Services", options: ["Banking", "Investment & Asset Management", "Insurance", "Accounting & Finance", "FinTech"] },
  { title: "Professional & Business Services", options: ["Consulting", "Legal Services", "HR & Staffing", "Marketing, Advertising & PR", "Business Services"] },
  { title: "Manufacturing & Industrial", options: ["Manufacturing", "Industrial Equipment & Machinery", "Automotive", "Aerospace & Defense", "Chemicals & Materials"] },
  { title: "Energy & Utilities", options: ["Oil & Gas", "Renewable Energy", "Utilities"] },
  { title: "Construction & Real Estate", options: ["Construction", "Engineering & Architecture", "Real Estate (Commercial & Residential)", "Property Management"] },
  { title: "Transportation & Logistics", options: ["Transportation", "Logistics & Supply Chain", "Aviation"] },
  { title: "Retail & Consumer Goods", options: ["Retail (In-store & E-commerce)", "Consumer Products", "Wholesale & Distribution"] },
  { title: "Food, Beverage & Hospitality", options: ["Food & Beverage", "Restaurants", "Hotels & Travel", "Special Events"] },
  { title: "Media, Entertainment & Sports", options: ["Media & Publishing", "Social Media", "Entertainment & Film", "Sports"] },
  { title: "Education & Research", options: ["Education (K-12 & Higher Ed)", "EdTech", "Training & Development", "Research Institutions"] },
  { title: "Government & Nonprofit", options: ["Government", "Public Sector", "Nonprofit & NGO", "Public Safety & Defense"] },
  { title: "Agriculture & Environmental", options: ["Agriculture & Food Systems", "Environmental Services", "Sustainability & Climate"] },
  { title: "Consumer & Personal Services", options: ["Personal Services", "Health, Fitness & Wellness", "Home & Repair Services"] },
  { title: "Other / Emerging Industries", options: ["Startups", "Climate Tech", "Space & Advanced Tech", "Other"] },
];

//doing this for options for company, will be shown as swatches on the profile
export const BACKGROUND_COLOR_OPTIONS = [
  { label: "Strawberry", value: "#df8484" },
  { label: "Crimson", value: "#DC2626" },
  { label: "Ruby", value: "#9F1239" },
  { label: "Light Orange", value: "#e9b06f" },
  { label: "Amber", value: "#D97706" },
  { label: "Gold", value: "#e0d53e" },
  { label: "Midnight", value: "#dab11d" },
  { label: "Mint Green", value: "#2bb59b" },
  { label: "Emerald", value: "#059669" },
  { label: "Forest", value: "#166534" },
  { label: "Electric Blue", value: "#2563EB" },
  { label: "Cobalt", value: "#1B4FD8" },
  { label: "Grey Blue", value: "#51608a" },
  { label: "Navy", value: "#0D1B2A" },
  { label: "Indigo", value: "#4338CA" },
  { label: "Lavender", value: "#9f89c4" },
  { label: "Violet", value: "#7C3AED" },
  { label: "White", value: "#e9e8e8" },
  { label: "Grey", value: "#aaa6a6" },
  { label: "Slate", value: "#334155" },
  { label: "Midnight", value: "#0A0A0A" },
];

//answers the question of how old the company is and how long it has been running for
export const COMPANY_AGE_OPTIONS = ["Up to 1", "1-3", "3-5", "5-10", "10+", "50+"];

export const WORK_TYPE_OPTIONS = ["Part-Time", "Full Time", "Contract", "All", "Currently not looking"];

export const WORK_PREFERENCE_OPTIONS = ["Remote", "Willing to relocate", "Both"];

//these will come down in the dropdown of the core values options that can be attached to company profile
export const CORE_VALUES = [
  "Accountability",
  "Adaptability",
  "Agility",
  "Collaboration",
  "Community Impact",
  "Continuous Learning",
  "Creativity",
  "Customer-First",
  "Data-Driven",
  "Discipline",
  "Diversity and Inclusion",
  "Employee Wellness",
  "Empowerment",
  "Excellence",
  "Inclusion",
  "Innovation",
  "Integrity",
  "Leadership Development",
  "Ownership",
  "Quality",
  "Research and Development",
  "Respect",
  "Results-Oriented",
  "Safety",
  "Social Responsibility",
  "Sustainability",
  "Teamwork",
  "Transparency",
  "Trust",
  "Work-Life Balance",
];

//this will be called when creating a role and should store as an array of skills like tags that will be later able to be filtered by a company to find relevant candidates in search
export const SKILLS: { title: string; options: string[] }[] = [
  {
    title: "Technology",
    options: [
      "Python", "JavaScript", "TypeScript", "Java", "C", "C++", "C#", "Go", "Rust", "Swift",
      "Kotlin", "Ruby", "PHP", "Scala", "R", "MATLAB", "Bash/Shell Scripting",
      "React", "React Native", "Next.js", "Vue.js", "Angular", "Node.js", "Django", "Flask",
      "Spring Boot", "GraphQL", "REST API Design", "gRPC",
      "AWS", "Azure", "Google Cloud Platform", "Docker", "Kubernetes", "Terraform", "CI/CD",
      "PostgreSQL", "MySQL", "MongoDB", "Redis", "Elasticsearch", "Snowflake", "BigQuery",
      "Machine Learning", "Deep Learning", "NLP", "Computer Vision", "PyTorch", "TensorFlow",
      "Data Engineering", "ETL Pipelines", "Apache Spark", "Kafka",
      "Cybersecurity", "Penetration Testing", "Network Security", "SIEM", "Cryptography",
      "Git", "Linux/Unix", "Agile/Scrum", "System Design", "Microservices Architecture",
      "Mobile Development", "Embedded Systems", "FPGA", "DevOps", "SRE",
      "UI/UX Design", "Figma", "Accessibility (WCAG)", "Technical Writing",
    ],
  },
  {
    title: "Healthcare & Life Sciences",
    options: [
      "Electronic Health Records (EHR/EMR)", "Epic", "Cerner", "HL7/FHIR",
      "Clinical Data Management", "Clinical Trials", "GCP (Good Clinical Practice)",
      "Medical Coding (ICD-10, CPT)", "Medical Billing", "HIPAA Compliance",
      "Patient Care", "Phlebotomy", "Vital Signs Monitoring", "IV Therapy",
      "Surgical Assistance", "Sterile Technique", "Medical Imaging", "Radiology",
      "Pharmacology", "Drug Dispensing", "Medication Reconciliation",
      "Lab Techniques (PCR, ELISA, Western Blot)", "Cell Culture", "Flow Cytometry",
      "Bioinformatics", "Genomics", "CRISPR", "Regulatory Affairs (FDA, CE Mark)",
      "Quality Assurance / Quality Control", "ISO 13485", "GMP (Good Manufacturing Practice)",
      "Public Health", "Epidemiology", "Biostatistics", "SAS", "R",
      "Medical Device Knowledge", "Healthcare Operations", "Care Coordination",
      "CPR/BLS/ACLS Certification", "HIPAA / PHI Handling", "Mental Health Assessment",
    ],
  },
  {
    title: "Financial Services",
    options: [
      "Financial Modeling", "Valuation (DCF, Comps, Precedent Transactions)",
      "Excel (Advanced)", "Bloomberg Terminal", "FactSet", "Capital IQ",
      "Accounting (GAAP/IFRS)", "Financial Reporting", "Auditing", "Tax Preparation",
      "QuickBooks", "SAP", "Oracle Financials", "NetSuite",
      "Risk Management", "Credit Analysis", "Underwriting", "Portfolio Management",
      "Derivatives", "Fixed Income", "Equity Research", "Investment Banking",
      "Python (Quantitative Finance)", "R", "SQL", "VBA",
      "Regulatory Compliance (SOX, Basel III, Dodd-Frank, KYC/AML)",
      "Actuarial Analysis", "Insurance Products", "Claims Processing",
      "Trading Platforms", "Algorithmic Trading", "FX/Forex",
      "CFA", "CPA", "Series 7 / Series 63", "CAIA",
      "Financial Planning & Analysis (FP&A)", "Budgeting & Forecasting",
      "Payment Systems", "Blockchain / DeFi", "Data Analysis",
    ],
  },
  {
    title: "Professional & Business Services",
    options: [
      "Project Management", "PMP Certification", "Agile / Scrum", "JIRA", "Asana",
      "Microsoft Office Suite", "Excel", "PowerPoint", "Word",
      "Business Analysis", "Requirements Gathering", "Process Mapping",
      "Consulting Frameworks", "Strategic Planning", "Change Management",
      "Data Analysis", "SQL", "Tableau", "Power BI", "Salesforce",
      "Legal Research", "Contract Drafting", "Compliance", "Due Diligence",
      "Human Resources", "Recruiting", "HRIS Systems", "Workday", "ADP",
      "Payroll", "Benefits Administration", "Labor Law",
      "Marketing Strategy", "Digital Marketing", "SEO/SEM", "Google Analytics",
      "Content Strategy", "Copywriting", "Brand Management",
      "Public Relations", "Stakeholder Management", "Executive Communication",
      "Six Sigma / Lean", "Business Development", "CRM Management",
      "Event Planning", "Vendor Management", "Supply Chain Operations",
    ],
  },
  {
    title: "Manufacturing & Industrial",
    options: [
      "CAD (AutoCAD, SolidWorks, CATIA, Inventor)", "CAM Software", "GD&T",
      "CNC Machining", "Lathe Operation", "Milling", "Welding (MIG, TIG, Stick)",
      "Sheet Metal Fabrication", "Injection Molding", "Casting & Forging",
      "Blueprint/Technical Drawing Reading", "Metrology & Inspection Tools",
      "Lean Manufacturing", "Six Sigma", "Kaizen", "5S", "Value Stream Mapping",
      "PLC Programming (Allen-Bradley, Siemens)", "SCADA Systems", "HMI",
      "Robotics / Automation", "Industrial IoT", "Predictive Maintenance",
      "Quality Control (QC)", "ISO 9001", "Statistical Process Control (SPC)",
      "FMEA", "Root Cause Analysis", "ERP Systems (SAP, Oracle)", "MRP",
      "Hydraulics & Pneumatics", "Electrical Systems", "Motor Controls",
      "Material Handling Equipment", "Forklift Certification", "OSHA 10/30",
      "Supply Chain Management", "Inventory Management", "BOM Management",
      "Thermodynamics", "Fluid Mechanics", "Mechanical Design",
    ],
  },
  {
    title: "Energy & Utilities",
    options: [
      "Electrical Engineering", "Power Systems", "Grid Operations", "SCADA",
      "High Voltage Systems", "Substation Operations", "Relay Protection",
      "Natural Gas Systems", "Pipeline Operations", "Compression & Flow Control",
      "Renewable Energy (Solar, Wind, Hydro)", "Energy Storage / Battery Systems",
      "NERC CIP Compliance", "FERC Regulations", "Environmental Compliance",
      "AutoCAD", "ETAP", "PSS/E", "GIS (Geographic Information Systems)",
      "Drilling Operations", "Well Completion", "Reservoir Engineering",
      "Petroleum Engineering", "Refinery Operations", "Process Safety Management",
      "Nuclear Safety", "Radiation Protection",
      "Energy Modeling", "Load Forecasting", "Demand Response",
      "Arc Flash Analysis", "Electrical Codes (NEC, NFPA 70E)",
      "Project Management", "PLC/DCS Programming", "Commissioning & Startup",
      "Field Operations", "Equipment Maintenance", "OSHA 30", "First Aid/CPR",
    ],
  },
  {
    title: "Construction & Real Estate",
    options: [
      "AutoCAD", "Revit (BIM)", "SketchUp", "Navisworks", "Civil 3D",
      "Blueprint Reading", "Structural Drawings", "MEP Coordination",
      "Construction Project Management", "Procore", "PlanGrid", "Bluebeam",
      "Estimating & Takeoffs", "Cost Control", "Scheduling (Primavera P6, MS Project)",
      "Site Supervision", "Quality Control Inspections", "Safety Management",
      "OSHA 10 / OSHA 30", "Fall Protection", "Scaffolding Safety",
      "Concrete Work", "Carpentry", "Masonry", "Plumbing", "Electrical Rough-In",
      "HVAC Installation", "Drywall & Framing", "Roofing",
      "Heavy Equipment Operation (Excavator, Crane, Bulldozer)",
      "Surveying & Layout", "Soil Testing & Grading",
      "Real Estate Transactions", "MLS", "Property Valuation / Appraisal",
      "Lease Agreements", "Property Management", "Zoning & Land Use",
      "Real Estate Law", "Title & Escrow", "Commercial Real Estate",
      "GIS / Site Analysis", "Environmental Assessment (Phase I/II)",
    ],
  },
  {
    title: "Transportation & Logistics",
    options: [
      "Supply Chain Management", "Logistics Operations", "Freight Brokerage",
      "Warehouse Management Systems (WMS)", "Transportation Management Systems (TMS)",
      "SAP", "Oracle SCM", "NetSuite", "ERP Systems",
      "Inventory Management", "Demand Planning", "S&OP",
      "Import/Export Compliance", "Customs Regulations", "Incoterms",
      "Freight Forwarding", "Ocean / Air / Ground Freight",
      "Route Optimization", "Last-Mile Delivery", "Fleet Management",
      "CDL (Commercial Driver's License)", "DOT Regulations", "HazMat Handling",
      "Forklift Certification", "OSHA 10", "Cold Chain Logistics",
      "Data Analysis", "Excel", "SQL", "Power BI", "Tableau",
      "Carrier Negotiations", "Vendor Management", "RFQ/RFP Process",
      "Aviation Operations", "Maritime / Port Operations", "Rail Operations",
      "E-Commerce Fulfillment", "Returns Management", "Cross-Docking",
    ],
  },
  {
    title: "Retail & Consumer Goods",
    options: [
      "Point of Sale (POS) Systems", "Inventory Management", "Merchandising",
      "Planogram Execution", "Visual Merchandising", "Retail Analytics",
      "Customer Service", "Sales Techniques", "Product Knowledge",
      "E-Commerce Platforms (Shopify, Magento, WooCommerce)", "Amazon Seller Central",
      "Digital Marketing", "Email Marketing", "Social Media Marketing",
      "Google Analytics", "SEO/SEM", "A/B Testing",
      "Supply Chain Operations", "Demand Forecasting", "Category Management",
      "Brand Management", "Product Development", "Consumer Insights",
      "Pricing Strategy", "Promotional Planning", "Trade Marketing",
      "CRM Systems", "Salesforce", "Customer Loyalty Programs",
      "Retail Loss Prevention", "Store Operations", "Team Leadership",
      "Excel", "Power BI", "Tableau", "SQL", "ERP Systems",
    ],
  },
  {
    title: "Food, Beverage & Hospitality",
    options: [
      "Food Safety & Sanitation", "ServSafe Certification", "HACCP",
      "Food Handling & Preparation", "Knife Skills", "Cooking Techniques",
      "Baking & Pastry", "Menu Development", "Recipe Costing",
      "Kitchen Equipment Operation", "Inventory & Ordering",
      "Restaurant Operations", "Front-of-House Management", "Table Service",
      "Bartending", "Wine & Beverage Knowledge", "Barista Skills",
      "POS Systems (Toast, Square, Aloha)", "Reservation Systems (OpenTable)",
      "Event Catering & Banquet Operations", "Hospitality Management",
      "Hotel Operations", "Property Management Systems (PMS)", "Revenue Management",
      "Guest Relations", "Conflict Resolution", "Upselling Techniques",
      "Food & Beverage Cost Control", "P&L Management",
      "Health Code Compliance", "Allergen Awareness", "Dietary Accommodations",
      "Team Leadership", "Scheduling & Workforce Management",
      "Travel & Tourism Knowledge", "Concierge Services",
    ],
  },
  {
    title: "Media, Entertainment & Sports",
    options: [
      "Video Production", "Cinematography", "Video Editing (Premiere Pro, DaVinci Resolve, Final Cut)",
      "Audio Production", "Sound Design", "Pro Tools", "Logic Pro",
      "Photography", "Adobe Lightroom", "Adobe Photoshop",
      "Graphic Design", "Adobe Illustrator", "InDesign", "After Effects",
      "Motion Graphics", "3D Modeling (Blender, Maya, Cinema 4D)",
      "Animation", "VFX / Visual Effects",
      "Scriptwriting", "Journalism", "Copywriting", "Content Creation",
      "Social Media Management", "YouTube / Streaming Platforms",
      "Podcast Production", "Live Streaming", "Broadcast Operations",
      "Sports Coaching", "Athletic Training", "Strength & Conditioning",
      "Sports Analytics", "Scouting & Recruiting",
      "Event Production", "Talent Management", "Licensing & Rights",
      "Digital Marketing", "Audience Development", "SEO",
      "Game Design", "Unity", "Unreal Engine",
      "Public Relations", "Community Management",
    ],
  },
  {
    title: "Education & Research",
    options: [
      "Curriculum Development", "Lesson Planning", "Instructional Design",
      "Classroom Management", "Differentiated Instruction", "Special Education",
      "Learning Management Systems (Canvas, Blackboard, Moodle)",
      "E-Learning Development (Articulate, Adobe Captivate)",
      "Student Assessment & Evaluation", "Academic Advising",
      "Research Methodology", "Quantitative Research", "Qualitative Research",
      "Statistical Analysis", "SPSS", "R", "Python", "SAS",
      "Academic Writing", "Grant Writing", "Literature Review",
      "Lab Research", "Scientific Writing", "Data Collection & Analysis",
      "IRB / Research Ethics", "Peer Review Process",
      "STEM Education", "Early Childhood Education", "Adult Education",
      "ESL / ELL Instruction", "Tutoring & Mentoring",
      "Higher Education Administration", "Student Affairs",
      "Library & Information Sciences", "Archival Research",
      "Policy Analysis", "Program Evaluation",
    ],
  },
  {
    title: "Government & Nonprofit",
    options: [
      "Policy Analysis & Development", "Legislative Research", "Regulatory Compliance",
      "Grant Writing", "Grant Management", "Federal Contracting / FAR",
      "Program Management", "Program Evaluation", "Logic Models",
      "Public Administration", "Budget Management", "Government Procurement",
      "Community Outreach", "Stakeholder Engagement", "Public Speaking",
      "Case Management", "Social Services", "Crisis Intervention",
      "Volunteer Management", "Fundraising", "Donor Relations",
      "Nonprofit Financial Management", "Form 990", "Fund Accounting",
      "Data Analysis", "GIS / Mapping", "Survey Design",
      "FOIA Requests", "Records Management", "Compliance Reporting",
      "Security Clearance (Secret / Top Secret)", "Intelligence Analysis",
      "Emergency Management", "FEMA / NIMS / ICS",
      "Advocacy & Lobbying", "Coalition Building",
      "Microsoft Office Suite", "Salesforce Nonprofit", "CRM",
      "Equity & Inclusion Practices", "Trauma-Informed Care",
    ],
  },
  {
    title: "Agriculture & Environmental",
    options: [
      "Crop Production & Agronomy", "Soil Science", "Irrigation Management",
      "Pest & Disease Management", "Integrated Pest Management (IPM)",
      "Livestock Management", "Animal Husbandry", "Veterinary Assistance",
      "Precision Agriculture", "GPS/GIS Mapping", "Drone Operation (Ag)",
      "Farm Equipment Operation (Tractors, Combines, Sprayers)",
      "Agricultural Chemistry", "Fertilizer Application",
      "Environmental Science", "Water Quality Analysis", "Air Quality Monitoring",
      "Environmental Impact Assessment", "NEPA Compliance",
      "Wetland Delineation", "Habitat Restoration", "Wildlife Biology",
      "Forestry & Timber Management", "Arboriculture",
      "Regulatory Compliance (EPA, Clean Water Act, Clean Air Act)",
      "GIS (ArcGIS, QGIS)", "Remote Sensing", "Environmental Sampling",
      "Sustainability Practices", "Carbon Accounting", "ESG Reporting",
      "Hydrology", "Stormwater Management", "Waste Management",
      "Food Safety (FSMA)", "Organic Certification", "AgTech Platforms",
    ],
  },
  {
    title: "Consumer & Personal Services",
    options: [
      "Customer Service", "CRM Software", "Conflict Resolution",
      "Appointment Scheduling", "Salon / Spa Software (Mindbody, Vagaro)",
      "Cosmetology", "Hair Cutting & Coloring", "Esthetics & Skincare",
      "Nail Technology", "Massage Therapy", "Personal Training",
      "Group Fitness Instruction", "Nutrition Coaching",
      "Childcare", "Early Childhood Education", "CPR/First Aid",
      "Elderly Care", "Companionship Services", "Memory Care",
      "Pet Grooming", "Dog Training", "Veterinary Assistance",
      "Cleaning & Sanitation", "Housekeeping Operations",
      "Tailoring & Alterations", "Dry Cleaning Operations",
      "Personal Shopping / Styling", "Image Consulting",
      "Driving (Rideshare / Chauffeur)", "Concierge Services",
      "Home Repair & Handyman Skills", "Appliance Repair",
      "Tech Support / IT Help Desk", "Point of Sale Systems",
      "Upselling & Retail Sales", "Inventory Management",
    ],
  },
  {
    title: "Other / Emerging Industries",
    options: [
      "Blockchain Development", "Smart Contracts (Solidity)", "Web3",
      "Cryptocurrency & DeFi", "NFT Platforms",
      "Artificial Intelligence / GenAI Tools", "Prompt Engineering",
      "AR / VR / XR Development", "Spatial Computing", "Unity", "Unreal Engine",
      "Quantum Computing", "Edge Computing", "IoT Development",
      "Drone Operation (Commercial)", "UAV Regulation (FAA Part 107)",
      "Space Systems", "Satellite Operations", "Aerospace Engineering",
      "Synthetic Biology", "Nanotechnology",
      "Cannabis Industry Operations", "Regulatory Compliance (Cannabis)",
      "Legal Tech", "LegalOps", "eDiscovery",
      "InsurTech", "HealthTech", "CleanTech / GreenTech",
      "3D Printing / Additive Manufacturing", "Materials Science",
      "Autonomous Vehicles", "LIDAR / Sensor Fusion",
      "Cybersecurity (Emerging Threats)", "Zero Trust Architecture",
      "Data Privacy (GDPR, CCPA)", "AI Ethics & Governance",
      "Entrepreneurship", "Startup Operations", "Venture Capital",
    ],
  },
];

//setting a constant here should only be able to have 5
export const MAX_CORE_VALUES = 5;

//for the ACCOUNT SECTION
export const ACCOUNT_PRIVACY_OPTIONS = ["Privacy", "Profile View", "Description"];

export const ACCOUNT_DETAIL_OPTIONS = ["Premium", "Details", "Summary", "Subscription"];

export const THEME_OPTIONS = ["Light Mode", "Dark Mode"];

//make it max 500 words
export const MISSION_STATEMENT_MAX_LENGTH = 500;

//benefits summary also max 500 words
export const BENEFITS_SUM_MAX_LENGTH = 500;

//management style summary/PTO
export const MANAGE_STYLE_MAX_LENGTH = 500;